<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE books SYSTEM "books.dtd">
<books>
    <book>
        <title name="Book Title">The Christmas Pig</title>
        <zipcode>12345</zipcode>
        <isbn no="98-8864567890"/>
        <publish year="1995">Hachette Children's Group in the UK</publish>
    </book>
    <book>
        <isbn no="98-88897654321"/>
        <author>V.V. Giri</author>
        <publish year="1995">Macmillan Company of India</publish>
    </book>
    <book>
        <zipcode>54321</zipcode>
        <isbn no="978-9876543210"/>
    </book>
</books>




<?xml version="1.0" encoding ="UTF-8" standalone="yes"?>
<!DOCTYPE BOOKS[
<!ELEMENT (book)>
<!ELEMENT book (title?, (zipcode | author), isbn+, publish*)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>
<!ELEMENT zipcode (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT publish (#PCDATA)>
<!ATTLIST title
    name CDATA #IMPLIED>
<!ATTLIST isbn
    no CDATA #REQUIRED>
<!ATTLIST zipcode
    Zname CDATA #FIXED "232232323">
<!ATTLIST publish
    year CDATA #FIXEDÂ "1995">
]>











]>